#!/bin/bash
demoFun(){
   echo "第一个shell函数"
}
echo "----函数开始执行----"
#demoFun
echo "----函数执行完毕----"
funWithReturn(){
    echo "这个函数会对输入的两个数字相加运算..."
    echo "输入第一个数字： "
    read aNum
    echo "输入第二个数字： "
    read bNum
    return $[ $aNum + $bNum ]
}
funWithReturn
echo "两个数字分别为 $? !"

funWithParam(){
    echo "第一个参数 $1 !"
    echo "第二个参数 $2 !"
    echo "第十个参数 $10 !"
    echo "第十个参数 ${10} !"
    echo "第十一个参数 ${11} !"
    echo "参数总数有 $# 个!"
    echo "$*"
    echo "$@"
}
funWithParam 1 2 3 4 5 6 7 8 9 34 73
