#!/bin/bash
val=`expr 2 + 2`
echo "两数之和 ： $val"
a=10
b=20
echo "a: $a, b: $b"
val=`expr $a + $b`
echo "a * b : $val"
val=`expr $a - $b`
echo "a - b : $val"
val=`expr $a \* $b`
echo "a * b : $val"
val=`expr $b / $a`
echo "b / a: $val"
val=`expr $b % $a`
echo "b % a: $val"
if [ $a == $b ]
then
    echo "a == b"
fi
if [ $a != $b ]
then
    echo "a != b"
fi

if [ $a -eq $b ]
then
    echo "a == b"
fi
if [ $a -ne $b ]
then
    echo "a != b"
fi
if [ $a -lt 100 -a $b -gt 15 ]
then
    echo "$a 小于 100 且 $b 大于15 ： 返回 true"
else
    echo "$a 小于 100 且 $b 大于15 ： 返回false"
fi
if [ $a -lt 5 -o $b -gt 100 ]
then
   echo "$a 小于 5 或 $b 大于 100 : 返回 true"
else
   echo "$a 小于 5 或 $b 大于 100 : 返回 false"
fi


if [ $a -lt 100 -a $b -gt 100 ]
then
   echo "返回 true"
else
   echo "返回 false"
fi

if [[ $a -lt 100 || $b -gt 100 ]]
then
   echo "返回 true"
else
   echo "返回 false"
fi
file="/home/ljdong/git_pro/Bash_demo/无标题文档"
if [ -r $file ]
then
    echo "文件可读"
else
    echo"文件不可读"
fi
if [ -w $file ]
then
   echo "文件可写"
else
   echo "文件不可写"
fi
if [ -x $file ]
then
   echo "文件可执行"
else
   echo "文件不可执行"
fi
if [ -f $file ]
then
   echo "文件为普通文件"
else
   echo "文件为特殊文件"
fi
if [ -d $file ]
then
   echo "文件是个目录"
else
   echo "文件不是个目录"
fi
if [ -s $file ]
then
   echo "文件不为空"
else
   echo "文件为空"
fi
if [ -e $file ]
then
   echo "文件存在"
else
   echo "文件不存在"
fi
read name name1
echo "$name It is a test $name1"
echo -e "OK! \n"
echo "It is a test"
echo -e "OK! \c"
echo "It is a test"
name="eman"
echo -e "$name\'"
echo `date`
echo -e "$name\n\c"

