#!/bin/bash
num1=100
num2=100
if test $[num1] -eq $[num2]
then
    echo "两个数相等！"
else
    echo "两个数不相等！"
fi
if [ $num1 -eq $num2 ]
then
    echo "两个数相等！"
else
    echo "两个数不相等！"
fi

a=5
b=6
result=$[a+b]
echo "result 为 ： $result"
num1="ru1noob"
num2="runoob"
if test $num1 = $num2
then
    echo '两个字符串相等!'
else
    echo '两个字符串不相等!'
fi
if [ $num1 == $num2 ]
then
    echo '两个字符串相等!'
else
    echo '两个字符串不相等!'
fi
