#!/bin/bash
if [ $(ps -ef | grep -c "ssh") -gt 1 ]; then echo "true"; fi
echo $(ps -ef | grep -c "ssh")
a=10
b=20
if [ $a == $b ]
then
    echo "a 等于 b"
elif [ $a -gt $b ]
then
    echo "a 大于 b "
elif [ $a -lt $b ]
then
    echo "a 小于 b "
else
    echo "没有符合条件"
fi
num1=$[2*3]
num2=$[1+5]
if test $[num1] -eq $[num2]
then
    echo '两个数字相等'
else
    echo '两个数字不相等'
fi
for loop in 1 2 3 4 5
do
    echo "The value is: $loop"
done
for str in 'This is a string'
do
    echo $str
done
int=1
while(( $int<=5 ))
do
   echo $int
   let "int++"
done
int=1
while test $[int] -le 5 
do
   echo $int
   let "int++"
done
:<<!
echo "按下 <CTRL-D> 退出"
echo -n "输入你喜欢的网址"

while read FILE
do
    echo "是的！ $FILE 是一个好网址"
done
!
echo "range(0,10):"
int=0
#until [ $int -eq 10 ]
until [ $int -gt 9 ]
do
    echo "$int"
#    int=$[int+1]
    int=`expr $int + 1`
done

echo "输入1到4间的数字："
echo "你输入的数字为： "
read aNum
case $aNum in
    1) echo "你选择了1"
    ;;
    2) echo "你选择了2"
    ;;
    3) echo "你选择了3"
    ;;
    4) echo "你选择了4"
    ;;
esac
while :
do
    echo -n "输入1到5之间的数字："
    read aNum
    case $aNum in
    1|2|3|4) echo "你输入的数字为: $aNum"
    ;;
    *) echo "输入数字非1-5 游戏结束"
	break
    ;;
    esac
done

site="runoob"

case $site in
   "runoob") echo "菜鸟教程"
   ;;
   "google") echo "Google 搜索"
   ;;
   "taobao") echo "淘宝网"
   ;;
esac
